// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oid85.FinMarket.Storage.Infrastructure.Database;

#nullable disable

namespace Oid85.FinMarket.Storage.Infrastructure.Migrations
{
    [DbContext(typeof(FinMarketContext))]
    [Migration("20260301062004_01032026_1")]
    partial class _01032026_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityAlwaysColumns(modelBuilder);

            modelBuilder.Entity("Oid85.FinMarket.Storage.Infrastructure.Database.Entities.BondCouponEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CouponDate")
                        .HasColumnType("date")
                        .HasColumnName("coupon_date");

                    b.Property<long>("CouponNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("coupon_number");

                    b.Property<int>("CouponPeriod")
                        .HasColumnType("integer")
                        .HasColumnName("coupon_period");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<double>("PayOneBond")
                        .HasColumnType("double precision")
                        .HasColumnName("pay_one_bond");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ticker");

                    b.HasKey("Id");

                    b.ToTable("BondCouponEntities", "public");
                });

            modelBuilder.Entity("Oid85.FinMarket.Storage.Infrastructure.Database.Entities.CandleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Close")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double>("High")
                        .HasColumnType("double precision");

                    b.Property<double>("Low")
                        .HasColumnType("double precision");

                    b.Property<double>("Open")
                        .HasColumnType("double precision");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Ticks")
                        .HasColumnType("bigint");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CandleEntities", "public");
                });

            modelBuilder.Entity("Oid85.FinMarket.Storage.Infrastructure.Database.Entities.ConsumerPriceIndexChangeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double?>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ConsumerPriceIndexChangeEntities", "public");
                });

            modelBuilder.Entity("Oid85.FinMarket.Storage.Infrastructure.Database.Entities.FundamentalParameterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("FundamentalParameterEntities", "public");
                });

            modelBuilder.Entity("Oid85.FinMarket.Storage.Infrastructure.Database.Entities.InstrumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CouponQuantityPerYear")
                        .HasColumnType("integer");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("LastPrice")
                        .HasColumnType("double precision");

                    b.Property<DateOnly?>("MaturityDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Nkd")
                        .HasColumnType("double precision");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InstrumentEntities", "public");
                });

            modelBuilder.Entity("Oid85.FinMarket.Storage.Infrastructure.Database.Entities.KeyRateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double?>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("KeyRateEntities", "public");
                });

            modelBuilder.Entity("Oid85.FinMarket.Storage.Infrastructure.Database.Entities.MonetaryAggregateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double?>("M0")
                        .HasColumnType("double precision");

                    b.Property<double?>("M1")
                        .HasColumnType("double precision");

                    b.Property<double?>("M2")
                        .HasColumnType("double precision");

                    b.Property<double?>("M2X")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("MonetaryAggregateEntities", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
