<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Hangfire" />
	  <PackageReference Include="Hangfire.InMemory" />	  
	  <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Oid85.FinMarket.TraderFinam.Common\Oid85.FinMarket.TraderFinam.Common.csproj" />
    <ProjectReference Include="..\Oid85.FinMarket.TraderFinam.Core\Oid85.FinMarket.TraderFinam.Core.csproj" />
  </ItemGroup>

</Project>
